config/routes.rb
Rails.application.routes.draw do
  root "birthdays#index"
  resources :birthdays, only: [ :index, :new, :create, :destroy ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/warmup", to: proc { ActiveRecord::Base.connection.execute("SELECT 1")
                            [ 200, {}, [ "OK" ] ]
                          }, as: :ping_to_keep_app_awake
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/birthday.rb
class Birthday < ApplicationRecord
  validates :first_name, :last_name, :date, presence: true
  scope :order_by_first_name, -> { order(first_name: :asc, last_name: :asc) }
  scope :order_by_last_name, -> { order(last_name: :asc, first_name: :asc) }
  scope :order_by_age, -> { order(date: :asc, first_name: :asc) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def age_last_birthday(on_date = Date.today)
    age = on_date.year - date.year
    age -= 1 if on_date < date + age.years
    age
  end

  def this_years_birthday
    today = Date.today
    Date.new(today.year, date.month, date.day)
  end

  def midpoint
    this_years_birthday + ((this_years_birthday.advance(years: 1) - this_years_birthday) / 2)
  end
end

app/models/birthday_with_upcoming.rb
class BirthdayWithUpcoming < Birthday
  self.table_name = "birthdays_with_upcoming"

  scope :order_by_upcoming_birthday, -> { order(:upcoming_birthday) }
  scope :order_by_upcoming_midpoint, -> { order(:upcoming_midpoint) }
  scope :upcoming_birthday_today, -> { where(upcoming_birthday: Date.today) }
  scope :upcoming_midpoint_today, -> { where(upcoming_midpoint: Date.today) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/birthdays_controller.rb
class BirthdaysController < ApplicationController
  VALID_SORTS = %w[first_name last_name age upcoming_birthday upcoming_midpoint]
  before_action :initialize_sort, only: :index

  def index
    @birthdays = BirthdayWithUpcoming.all
    handle_sort
    handle_response
  end

  def new
    @birthday = Birthday.new
  end

  def create
    @birthday = Birthday.new(birthday_params)

    if @birthday.save
      flash[:success] = "Birthday was successfully added."
      redirect_to birthdays_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @birthday = Birthday.find(params.expect(:id))
    @birthday.destroy!

    flash[:success] = "Birthday was successfully deleted."
    redirect_to birthdays_path
  end

  private

    def initialize_sort
      session[:birthday_sort_option] = params[:birthday_sort_option] || session[:birthday_sort_option]
    end

    def handle_sort
      sort_option = session[:birthday_sort_option]
      sort_option = "upcoming_birthday" unless VALID_SORTS.include?(sort_option)
      @birthdays = @birthdays.send("order_by_#{sort_option}")
    end

    def handle_response
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    end

    def birthday_params
      params.expect(birthday: [ :first_name, :last_name, :date ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthdays_helper.rb
module BirthdaysHelper
end

app/views/birthdays/_birthday.html.erb
<div class="table-row" id="<%= dom_id birthday %>" >
    <div class="full-name"><%= birthday.full_name %></div>
    <div class="birthday"><span>🎁</span><%= birthday.date.strftime('%d %b %Y') %></div>
    <div class="birthday"><span>🎯</span><%= birthday.upcoming_midpoint.strftime('%d %b') %></div>
    <div class="age"><span class='age-badge'><%= birthday.age_last_birthday %></span></div>
    <div class="function"><%= link_to image_tag("dustbin.webp", class: "table_icon", alt: 'Delete Birthday'), birthday_path(birthday.id), data: { turbo_method: :delete } %></div>
</div>

app/views/birthdays/_birthdays_table.html.erb
<div id="birthdays-table" class="birthday-table">
  <!--div class="table-header">
    <div class="first-name">First Name</div>
    <div class="last-name">Last Name</div>
    <div class="birthday">Birthday</div>
    <div class="function"></div>
  </div-->
  <%= render partial: 'birthdays/birthday', collection: @birthdays %>
</div>

app/views/birthdays/_empty_table_message.html.erb
<p class='mt-3'>You have not added any birthdays yet.</p>

app/views/birthdays/_form.html.erb
<%= form_with(model: birthday) do |form| %>
  <% if birthday.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(birthday.errors.count, "error") %> prohibited this birthday from being saved:</h2>

      <ul>
        <% birthday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/birthdays/_sort_selection.html.erb
<form action="/birthdays" method="GET">
  <div class="mt-0">
    <i class="bi bi-sort-alpha-down"></i>
    <select class="form-control-sm mb-2 sort" name="birthday_sort_option" onchange="this.form.requestSubmit()">
      <option disabled="disabled" selected="selected" value="">Sort by</option>
      <option value="first_name" <%="selected" if session[:birthday_sort_option] == "first_name"%> >first name</option>
      <option value="last_name" <%="selected" if session[:birthday_sort_option] == "last_name"%> >last name</option>
      <option value="age" <%="selected" if session[:birthday_sort_option] == "age"%> >age</option>
      <option value="upcoming_birthday" <%="selected" if session[:birthday_sort_option] == "upcoming_birthday"%> >upcoming birthday</option>
      <option value="upcoming_midpoint" <%="selected" if session[:birthday_sort_option] == "upcoming_midpoint"%> >upcoming midpoint</option>
    </select>
  </div>
</form>

app/views/birthdays/edit.html.erb
<% content_for :title, "Editing birthday" %>

<h1>Editing birthday</h1>

<%= render "form", birthday: @birthday %>

<br>

<div>
  <%= link_to "Show this birthday", @birthday %> |
  <%= link_to "Back to birthdays", birthdays_path %>
</div>

app/views/birthdays/index.html.erb
<div class="container px-1">
  <% content_for :title, "Birthdays" %>
  <h1 class='mb-3 mb-md-1'>
  <%= link_to new_birthday_path, data: { turbo_frame: dom_id(Birthday.new)}, alt: 'New Birthday', class: 'btn add-button' do %>
                              <i class="bi bi-plus-lg me-md-1"></i><span>Birthday 🎁 🎈</span><% end %> </h1>
  <%= turbo_frame_tag Birthday.new do %>
    <% render 'empty_table_message' if @birthdays.empty? %>
  <% end %>
  <%= turbo_frame_tag 'items-and-filter' do %>
    <%= render 'sort_selection' unless @birthdays.empty? %> 
    <%= turbo_frame_tag 'birthdays' do %>
      <%= render 'birthdays_table' unless @birthdays.empty? %>
    <% end %>
  <% end %>
</div>

app/views/birthdays/index.turbo_stream.erb
<%= turbo_stream.update "birthdays" do %>
  <%= render partial: "birthdays_table" %>
<% end %>
<%= turbo_stream.update "new_birthday" do %>
  <%= render inline:'' %>
<% end %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/birthdays/new.html.erb
<% content_for :title, "New league" %>
<%= turbo_frame_tag @birthday do %>
  <div class="col-md-6 mb-4">
    <%= render "form", birthday: @birthday %>
  </div>
<% end %>

app/views/birthdays/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @birthday %>

<div>
  <%= link_to "Edit this birthday", edit_birthday_path(@birthday) %> |
  <%= link_to "Back to birthdays", birthdays_path %>

  <%= button_to "Destroy this birthday", @birthday, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
    <% bootstrap_class = case flash_type.to_sym
       when :notice then "success"
       when :alert  then "danger"
       when :error  then "danger"
       else flash_type
    end %>
  <div class="flash__message alert alert-<%= bootstrap_class %>"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Remind" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Remind">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id='flash' class="flash">  
      <%= render "layouts/flash" %>
    </div>    
    <%= yield %>
  </body>
</html>